namespace: pycrest

image:
  repository: chillmadiguys/loan-service
  tag: v1.1.0
  pullPolicy: Always

replicaCount: 2
minReadySeconds: 20

service:
  port: 8000

resources:
  requests:
    cpu: 200m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 1Gi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  cpuThreshold: 70
  memoryThreshold: 85

serviceAccount:
  name: loan-service-sa

configMapName: pycrest-global-config
secretName: pycrest-global-secret
pvcName: pycrest-uploads-pvc