apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
  namespace: pc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loan-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: loan-service
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                  - loan-service
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: loan-container
          image: chillmadiguys/loan-service:v1.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: pc-config-global
            - secretRef:
                name: pc-secrets-global
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          #   # timeoutSeconds: 2
          #   # failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          #   # timeoutSeconds: 2
          #   # failureThreshold: 3
          volumeMounts:
            - name: loan-volume
              mountPath: /app/uploads
      volumes:
        - name: loan-volume
          persistentVolumeClaim:
            claimName: pc-upload-pvc
          