EMI_STATUS_PENDING = "pending"
EMI_STATUS_PAID = "paid"
EMI_STATUS_OVERDUE = "overdue"
EMI_STATUS_DEFAULTED = "defaulted"
EMI_STATUS_WAIVED = "waived"

EMI_ESCALATION_OPEN = "open"
EMI_ESCALATION_CLOSED = "closed"

DEFAULT_EMI_GRACE_DAYS = 3
DEFAULT_PENALTY_RATE = 0.02
DEFAULT_FREEZE_AFTER_MISSED = 2